# Generated by Django 4.0.6 on 2022-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='creator_id',
        ),
    ]
