# Generated by Django 4.0.6 on 2022-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_remove_diagram_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='diagram_name',
            field=models.CharField(default='', max_length=100, verbose_name='绘图名称'),
        ),
    ]
