# Generated by Django 4.0.6 on 2022-08-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_alter_diagram_diagram_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='diagram_name',
        ),
        migrations.AddField(
            model_name='diagram',
            name='diagram_content',
            field=models.TextField(null=True, verbose_name='绘图内容'),
        ),
    ]
