# Generated by Django 4.0.6 on 2022-08-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_remove_diagram_diagram_name_diagram_diagram_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='diagram_name',
            field=models.CharField(default='', max_length=100, verbose_name='绘图名称'),
        ),
    ]
