# Generated by Django 4.0.6 on 2022-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=30, verbose_name='页面名称')),
                ('page_height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='页面高度')),
                ('page_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='页面宽度')),
                ('element_list', models.TextField(default='', verbose_name='页面样式')),
                ('num', models.IntegerField(default='', verbose_name='页面特征值')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserToPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='人员id')),
                ('page_id', models.IntegerField(default=0, verbose_name='页面id')),
            ],
        ),
    ]
