# Generated by Django 4.0.6 on 2022-08-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='num',
            field=models.IntegerField(default=0, verbose_name='页面特征值'),
        ),
    ]
