# Generated by Django 4.0.6 on 2022-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(default='', max_length=100, verbose_name='页面名称'),
        ),
    ]
