# Generated by Django 4.1 on 2022-08-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_is_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToPage',
        ),
    ]
