# Generated by Django 4.1 on 2022-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_delete_usertopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_preview',
            field=models.IntegerField(default=0, verbose_name='是否预览'),
        ),
    ]
