# Generated by Django 4.1 on 2022-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_page_is_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('page_id', models.IntegerField(default=0, verbose_name='页面id')),
            ],
        ),
    ]
