# Generated by Django 4.1 on 2022-08-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_usertopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelToPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='项目id')),
                ('page_id', models.IntegerField(default=0, verbose_name='页面id')),
            ],
        ),
    ]
