# Generated by Django 4.1 on 2022-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_modeltopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltopage',
            name='model_name',
            field=models.CharField(default='', max_length=100, verbose_name='页面名称'),
        ),
    ]
