# Generated by Django 4.1 on 2022-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_projectmodel_remove_modeltopage_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('model_name', models.CharField(default='', max_length=100, verbose_name='页面名称')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
