# Generated by Django 4.1 on 2022-08-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_usermodel_delete_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_public',
            field=models.IntegerField(default=0, verbose_name='是否是共有的'),
        ),
    ]
