# Generated by Django 4.0.6 on 2022-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='', max_length=30, verbose_name='项目简介'),
        ),
    ]
