# Generated by Django 4.0.6 on 2022-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='项目id')),
                ('page_id', models.IntegerField(default=0, verbose_name='页面id')),
            ],
        ),
    ]
