# Generated by Django 4.0.6 on 2022-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projecttopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='', max_length=1000, verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=100, verbose_name='项目名称'),
        ),
    ]
