# Generated by Django 4.0.6 on 2022-08-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_num',
        ),
    ]
