# Generated by Django 4.0.6 on 2022-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_file_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_id',
            field=models.IntegerField(default=0, verbose_name='项目创建者id'),
        ),
        migrations.AddField(
            model_name='project',
            name='create_name',
            field=models.CharField(default='', max_length=1000, verbose_name='项目创建者姓名'),
        ),
    ]
