# Generated by Django 4.0.6 on 2022-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_create_id_project_create_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_folder_id',
            field=models.IntegerField(default=0, verbose_name='项目文件夹id'),
        ),
    ]
