# Generated by Django 4.0.6 on 2022-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_content',
            field=models.TextField(default='', verbose_name='文档内容'),
        ),
    ]
