# Generated by Django 4.0.6 on 2022-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_document_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('document_id', models.IntegerField(default=0, verbose_name='文档id')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='creator_id',
            field=models.IntegerField(default=0, verbose_name='创建者id'),
        ),
    ]
