# Generated by Django 4.0.6 on 2022-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_projecttodocument_remove_document_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_title',
            field=models.CharField(default='', max_length=100, verbose_name='文档标题'),
        ),
    ]
