# Generated by Django 4.0.6 on 2022-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creator_name',
            field=models.IntegerField(default=0, verbose_name='创建者名称'),
        ),
    ]
