# Generated by Django 4.0.6 on 2022-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_document_creator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creator_name',
            field=models.CharField(default='', max_length=100, verbose_name='创建者名称'),
        ),
    ]
