# Generated by Django 4.0.6 on 2022-08-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_document_is_folder_or_file_document_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='team_id',
            field=models.IntegerField(default=0, verbose_name='团队id'),
        ),
    ]
