# Generated by Django 4.0.6 on 2022-08-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_document_team_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectToDocument',
        ),
        migrations.RemoveField(
            model_name='document',
            name='project_id',
        ),
    ]
