# Generated by Django 4.0.6 on 2022-08-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_delete_projecttodocument_remove_document_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_folder_or_file',
            new_name='document_type',
        ),
    ]
