# Generated by Django 4.0.6 on 2022-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_rename_is_folder_or_file_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_content', models.TextField(default='', verbose_name='文档内容')),
            ],
        ),
    ]
