# Generated by Django 4.0.6 on 2022-08-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_documentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentModel',
        ),
    ]
