# Generated by Django 4.0.6 on 2022-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user_num',
            field=models.IntegerField(default=1, verbose_name='成员的数量'),
        ),
    ]
