# Generated by Django 4.0.6 on 2022-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_user_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_num',
            field=models.IntegerField(default=0, verbose_name='项目的数量'),
        ),
    ]
