# Generated by Django 4.0.6 on 2022-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teamtoproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='', max_length=100, verbose_name='团队名称'),
        ),
    ]
