# Generated by Django 4.0.6 on 2022-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_folder_id',
            field=models.IntegerField(default=0, verbose_name='团队文件夹'),
        ),
    ]
