# Generated by Django 4.0.6 on 2022-07-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superAdmin',
            new_name='is_super_admin',
        ),
    ]
