# Generated by Django 4.0.6 on 2022-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_superadmin_user_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_num',
            field=models.IntegerField(default=0, verbose_name='站内信的数量'),
        ),
    ]
