# Generated by Django 4.0.6 on 2022-07-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_message_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='', upload_to='', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='', max_length=128, verbose_name='用户头像路径'),
        ),
    ]
