# Generated by Django 4.0.6 on 2022-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_avatar_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='message_num',
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=30, verbose_name='真实性名'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_num',
            field=models.IntegerField(default=0, verbose_name='团队的数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='用户名'),
        ),
    ]
