# Generated by Django 4.0.6 on 2022-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_is_super_admin_remove_user_message_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('team_id', models.IntegerField(default=0, verbose_name='团队id')),
                ('is_super_admin', models.IntegerField(default=0, verbose_name='是否是团队管理员')),
            ],
        ),
    ]
