# Generated by Django 4.0.6 on 2022-08-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usertoteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToProjectStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('project_id', models.IntegerField(default=0, verbose_name='项目id')),
                ('is_delete', models.IntegerField(default=0, verbose_name='是否删除')),
            ],
        ),
    ]
